name: flutter_peer
description: A Flutter plugin that simplifies peer-to-peer communication using WebRTC, supporting signaling, media streams, and real-time events.
version: 0.0.2

homepage: https://github.com/vikassharmanaini/flutter_peer
repository: https://github.com/vikassharmanaini/flutter_peer
issue_tracker: https://github.com/vikassharmanaini/flutter_peer/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.2
  plugin_platform_interface: ^2.0.2
  flutter_webrtc: ^1.2.1
  web_socket_channel: ^3.0.1
  eventify: ^1.0.1
  uuid: ^4.2.2
  web: ^1.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_peer
        pluginClass: FlutterPeerPlugin
      ios:
        pluginClass: FlutterPeerPlugin
      web:
        pluginClass: FlutterPeerWeb
        fileName: peer_web.dart
